// 根文件，存放操作类型
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_WEALTH_SUCCESS = 'GET_WEALTH_SUCCESS';
export const GET_RECOMMEND_SUCCESS = 'GET_RECOMMEND_SUCCESS';
export const GET_POINT_SUCCESS = 'GET_POINT_SUCCESS';
export const GET_POINTSRECORD_SUCCESS = 'GET_POINTSRECORD_SUCCESS';
export const GET_TRADELIST_SUCCESS = 'GET_TRADELIST_SUCCESS';
export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';
export const GET_TRADEINFO_SUCCESS = 'GET_TRADEINFO_SUCCESS';
export const GET_ACCOUNTINFO_SUCCESS = 'GET_ACCOUNTINFO_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_HXTRADEINFO_SUCCESS='GET_HXTRADEINFO_SUCCESS';
// export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'